export const ApiRoutes = {
    auth: "/user/oauth",
    callback:"/callback",
    redirect:"/redirect",
    backupToken: "/backup/token",
    allInvoice : "/invoice/all",
    allItem : "/item/all",
    allAccount : "/account/all",
    allVendor : "/vendor/all",
    allCustomer : "/customer/all",
    allEmployee : "/employee/all",
    allDepartement : "/departement/all",
    allJournalEntry : "/journal/all",
    allBudget : "/budget/all",
    allPaiement : "/paiement/all",
    allReportListAccount : "/rapport/account/all",
    getInvoiceById : "/invoice/",
    getSalesItemLineDetailsInvoice : "/sales/item/line/detail/invoice",
}